# This file has been generated by mavenix-2.3.3. Configure the build here!
let
  mavenix-src = fetchTarball { url = "https://github.com/nix-community/mavenix/tarball/v2.3.3"; sha256 = "1l653ac3ka4apm7s4qrbm4kx7ij7n2zk3b67p9l0nki8vxxi8jv7"; };
  lock = builtins.fromJSON (builtins.readFile ./flake.lock);
  flake = (import (fetchTarball {
    url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
    sha256 = lock.nodes.flake-compat.locked.narHash;
  }) { src = ./.; }).defaultNix;
in {
  pkgs ? import flake.inputs.nixpkgs {},
  mavenix ? import mavenix-src { inherit pkgs; },
  src ? ./.,
  doCheck ? false,
}: mavenix.buildMaven {
  inherit src doCheck;
  infoFile = ./mavenix.lock;
  jdk = pkgs.graalvm-ce;

  # Add build dependencies
  #
  buildInputs = with pkgs; [ git ];

  # Set build environment variables
  #
  MAVEN_OPTS = "-Dfile.encoding=UTF-8 -Dbuild_number=nix";

  # Attributes are passed to the underlying `stdenv.mkDe:wqrivation`, so build
  #   hooks can be set here also.
  installPhase = ''
      install -Dm775 ./cli-native/target/mconv $out/bin/mconv
  '';

  #
  maven = pkgs.maven.overrideAttrs (_: { jdk = pkgs.graalvm-ce; });

}
